/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char126_unauthenticatedIndexRouteImport } from './routes/~_unauthenticated/index'
import { Route as Char126_authenticatedIndexRouteImport } from './routes/~_authenticated/index'
import { Route as Char126_unauthenticatedChar126loginIndexRouteImport } from './routes/~_unauthenticated/~login/index'
import { Route as Char126_unauthenticatedChar126loginComponentsLoginRouteImport } from './routes/~_unauthenticated/~login/components/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126_unauthenticatedIndexRoute =
  Char126_unauthenticatedIndexRouteImport.update({
    id: '/~_unauthenticated/',
    path: '/~_unauthenticated/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char126_authenticatedIndexRoute =
  Char126_authenticatedIndexRouteImport.update({
    id: '/~_authenticated/',
    path: '/~_authenticated/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char126_unauthenticatedChar126loginIndexRoute =
  Char126_unauthenticatedChar126loginIndexRouteImport.update({
    id: '/~_unauthenticated/~login/',
    path: '/~_unauthenticated/~login/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char126_unauthenticatedChar126loginComponentsLoginRoute =
  Char126_unauthenticatedChar126loginComponentsLoginRouteImport.update({
    id: '/~_unauthenticated/~login/components/login',
    path: '/~_unauthenticated/~login/components/login',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/~_authenticated/': typeof Char126_authenticatedIndexRoute
  '/~_unauthenticated/': typeof Char126_unauthenticatedIndexRoute
  '/~_unauthenticated/~login/': typeof Char126_unauthenticatedChar126loginIndexRoute
  '/~_unauthenticated/~login/components/login': typeof Char126_unauthenticatedChar126loginComponentsLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/~_authenticated': typeof Char126_authenticatedIndexRoute
  '/~_unauthenticated': typeof Char126_unauthenticatedIndexRoute
  '/~_unauthenticated/~login': typeof Char126_unauthenticatedChar126loginIndexRoute
  '/~_unauthenticated/~login/components/login': typeof Char126_unauthenticatedChar126loginComponentsLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/~_authenticated/': typeof Char126_authenticatedIndexRoute
  '/~_unauthenticated/': typeof Char126_unauthenticatedIndexRoute
  '/~_unauthenticated/~login/': typeof Char126_unauthenticatedChar126loginIndexRoute
  '/~_unauthenticated/~login/components/login': typeof Char126_unauthenticatedChar126loginComponentsLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/~_authenticated/'
    | '/~_unauthenticated/'
    | '/~_unauthenticated/~login/'
    | '/~_unauthenticated/~login/components/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/~_authenticated'
    | '/~_unauthenticated'
    | '/~_unauthenticated/~login'
    | '/~_unauthenticated/~login/components/login'
  id:
    | '__root__'
    | '/'
    | '/~_authenticated/'
    | '/~_unauthenticated/'
    | '/~_unauthenticated/~login/'
    | '/~_unauthenticated/~login/components/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char126_authenticatedIndexRoute: typeof Char126_authenticatedIndexRoute
  Char126_unauthenticatedIndexRoute: typeof Char126_unauthenticatedIndexRoute
  Char126_unauthenticatedChar126loginIndexRoute: typeof Char126_unauthenticatedChar126loginIndexRoute
  Char126_unauthenticatedChar126loginComponentsLoginRoute: typeof Char126_unauthenticatedChar126loginComponentsLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~_unauthenticated/': {
      id: '/~_unauthenticated/'
      path: '/~_unauthenticated'
      fullPath: '/~_unauthenticated/'
      preLoaderRoute: typeof Char126_unauthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~_authenticated/': {
      id: '/~_authenticated/'
      path: '/~_authenticated'
      fullPath: '/~_authenticated/'
      preLoaderRoute: typeof Char126_authenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~_unauthenticated/~login/': {
      id: '/~_unauthenticated/~login/'
      path: '/~_unauthenticated/~login'
      fullPath: '/~_unauthenticated/~login/'
      preLoaderRoute: typeof Char126_unauthenticatedChar126loginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~_unauthenticated/~login/components/login': {
      id: '/~_unauthenticated/~login/components/login'
      path: '/~_unauthenticated/~login/components/login'
      fullPath: '/~_unauthenticated/~login/components/login'
      preLoaderRoute: typeof Char126_unauthenticatedChar126loginComponentsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char126_authenticatedIndexRoute: Char126_authenticatedIndexRoute,
  Char126_unauthenticatedIndexRoute: Char126_unauthenticatedIndexRoute,
  Char126_unauthenticatedChar126loginIndexRoute:
    Char126_unauthenticatedChar126loginIndexRoute,
  Char126_unauthenticatedChar126loginComponentsLoginRoute:
    Char126_unauthenticatedChar126loginComponentsLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
