/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentdashboardRouteImport } from './routes/studentdashboard'
import { Route as IndexRouteImport } from './routes/index'

const StudentdashboardRoute = StudentdashboardRouteImport.update({
  id: '/studentdashboard',
  path: '/studentdashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studentdashboard': typeof StudentdashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studentdashboard': typeof StudentdashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studentdashboard': typeof StudentdashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studentdashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studentdashboard'
  id: '__root__' | '/' | '/studentdashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentdashboardRoute: typeof StudentdashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studentdashboard': {
      id: '/studentdashboard'
      path: '/studentdashboard'
      fullPath: '/studentdashboard'
      preLoaderRoute: typeof StudentdashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentdashboardRoute: StudentdashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
